// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.6
// source: srpc.proto

package srpc

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type HttpRouteOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path *string `protobuf:"bytes,1,opt,name=path,proto3,oneof" json:"path,omitempty"`
}

func (x *HttpRouteOptions) Reset() {
	*x = HttpRouteOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_srpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpRouteOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRouteOptions) ProtoMessage() {}

func (x *HttpRouteOptions) ProtoReflect() protoreflect.Message {
	mi := &file_srpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRouteOptions.ProtoReflect.Descriptor instead.
func (*HttpRouteOptions) Descriptor() ([]byte, []int) {
	return file_srpc_proto_rawDescGZIP(), []int{0}
}

func (x *HttpRouteOptions) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

var file_srpc_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*HttpRouteOptions)(nil),
		Field:         1000,
		Name:          "srpc.method_option_http_api",
		Tag:           "bytes,1000,opt,name=method_option_http_api",
		Filename:      "srpc.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional srpc.HttpRouteOptions method_option_http_api = 1000;
	E_MethodOptionHttpApi = &file_srpc_proto_extTypes[0]
)

var File_srpc_proto protoreflect.FileDescriptor

var file_srpc_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x73, 0x72,
	0x70, 0x63, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x10, 0x48, 0x74, 0x74, 0x70, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x17, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x88, 0x01,
	0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x3a, 0x6f, 0x0a, 0x16, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x68, 0x74, 0x74, 0x70,
	0x5f, 0x61, 0x70, 0x69, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0xe8, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x72,
	0x70, 0x63, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x13, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x48, 0x74, 0x74, 0x70, 0x41, 0x70, 0x69, 0x88, 0x01, 0x01, 0x42, 0x08, 0x5a, 0x06, 0x2e,
	0x3b, 0x73, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_srpc_proto_rawDescOnce sync.Once
	file_srpc_proto_rawDescData = file_srpc_proto_rawDesc
)

func file_srpc_proto_rawDescGZIP() []byte {
	file_srpc_proto_rawDescOnce.Do(func() {
		file_srpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_srpc_proto_rawDescData)
	})
	return file_srpc_proto_rawDescData
}

var file_srpc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_srpc_proto_goTypes = []interface{}{
	(*HttpRouteOptions)(nil),           // 0: srpc.HttpRouteOptions
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_srpc_proto_depIdxs = []int32{
	1, // 0: srpc.method_option_http_api:extendee -> google.protobuf.MethodOptions
	0, // 1: srpc.method_option_http_api:type_name -> srpc.HttpRouteOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_srpc_proto_init() }
func file_srpc_proto_init() {
	if File_srpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_srpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpRouteOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_srpc_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_srpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_srpc_proto_goTypes,
		DependencyIndexes: file_srpc_proto_depIdxs,
		MessageInfos:      file_srpc_proto_msgTypes,
		ExtensionInfos:    file_srpc_proto_extTypes,
	}.Build()
	File_srpc_proto = out.File
	file_srpc_proto_rawDesc = nil
	file_srpc_proto_goTypes = nil
	file_srpc_proto_depIdxs = nil
}
